vets:
  cache:
    ttl: 60
    heap-size: 100

---
spring:
  config:
    activate:
      on-profile: default
eureka:
  instance:
    # enable to register multiple app instances with a random server port
    instance-id: ${spring.application.name}:${random.uuid}

---
spring:
  config:
    activate:
      on-profile: docker
server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server.petclinic-namespace:8761/eureka/
